apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/quantumx/
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: quantumx
    path: patch.yaml