apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./templates/deployment.yaml
- ./templates/service.yaml
- ./charts/postgresql/templates/secrets.yaml
- ./charts/postgresql/templates/primary/statefulset.yaml
- ./charts/postgresql/templates/primary/svc-headless.yaml
- ./charts/postgresql/templates/primary/svc.yaml
