# QuantumX/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quantumx
  labels:
    app: quantumx
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: quantumx
  template:
    metadata:
      labels:
        app: quantumx
    spec:
      containers:
        - name: quantumx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.service.port }}